[package]
distribution = "2201.13.6"
org = "ballerinax"
name = "salesforce.pubsub"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Cost/Freemium", "Vendor/Salesforce", "Area/CRM & Sales", "Type/Connector", "Type/Trigger"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-salesforce.pubsub"
include = ["metadata/**"]

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
